name: CI for StarRail-Gacha
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.10

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install nuitka
        run: |
          pip install nuitka

      - name: Build
        run: |
          nuitka --mingw64 --enable-plugin=pyqt5 --standalone --windows-icon-from-ico=.\src\resources\star_rail.ico --output-dir=build --output-filename="StarRail Gacha Exporter" .\src\__main__.py
          xcopy .\src\resources\ .\build\__main__.dist\resources /y

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: StarRail Gacha Exporter-dev
          path: build\__main__.dist\*
          
