name: CI for StarRail-Gacha
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install nuitka
        run: |
          pip install nuitka

      - name: Build
        run: |
          powershell -noprofile -command (nuitka --mingw64 --windows-disable-console --enable-plugin=pyqt5 --standalone --windows-icon-from-ico=.\src\resources\star_rail.ico --output-dir=build --output-filename="StarRail Gacha Exporter" .\src\main.py) -and (Copy-Item -Path .\src\resources\ -Destination .\build\main.dist\ -Recurse -Force) -or (Compress-Archive -Path .\build\main.dist\ .\build\"StarRail Gacha Exporter.zip" -Force)

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: StarRail Gacha Exporter
          path: build/"StarRail Gacha Exporter.zip"
