name: CI for StarRail Gacha Exporter
on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4

      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install nuitka
        run: |
          pip install nuitka

      - name: Build
        run: nuitka --windows-disable-console --assume-yes-for-downloads --enable-plugin=pyqt5 --lto="yes" --static-libpython="yes" --standalone --windows-icon-from-ico=.\src\resources\star_rail.ico --output-dir=build --output-filename="StarRail Gacha Exporter" .\src\main.py

      - name: Copy resources and zip
        run: |
          powershell Copy-Item -Path .\src\resources\ -Destination .\build\main.dist\ -Recurse -Force
          powershell Compress-Archive -Path .\build\main.dist\ .\build\\"StarRail-Gacha-Exporter.zip" -Force

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: StarRail-Gacha-Exporter
          path: build\StarRail-Gacha-Exporter.zip

