name: Update Crowdin Translate
on:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions: write-all

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.10'

      - name: Install PtQt5-tool
        run: pip install PyQt5-tools

      - name: Generate i18n source file
        run: |
          cd src/star_rail_gacha
          pylupdate5 star_rail_gacha.pro

      - uses: crowdin/github-action@v1.19.0
        with:
          upload_sources: true
          download_translations: true
          push_translations: true
          commit_message: New Crowdin translations by GitHub Action
          localization_branch_name: master
          create_pull_request: false
          download_translations_args: --all
          project_id: 590371
          token: ${{ secrets.CROWDIN_API_TOKEN }}
          base_url: https://api.crowdin.com
          base_path: src/resources/i18n
          source: /source.ts
          translation: /%locale%/%original_file_name%
          preserve_hierarchy: true

      - name: Find site-packages path
        id: find_path
        run: python .github/workflows/scripts/lib_path.py >> "$GITHUB_OUTPUT"

      - name: Release i18n files
        env:
          LIB_PATH: ${{ steps.find_path.outputs.lib_path }}
        run: sh ./.github/workflows/scripts/release_i18n.sh

      - name: Commit released i18n files
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.qm'
          message: 'New released i18n files from Actions'
